apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odewahn-todo-app-db-pvc
  namespace: odewahn-todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
